# Generated by Django 5.2.11 on 2026-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='autopilot_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='shortlist_threshold',
            field=models.IntegerField(default=80),
        ),
    ]
