# Generated by Django 5.2.11 on 2026-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_vacancy_autopilot_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='max_hires',
            field=models.IntegerField(default=2),
        ),
    ]
