# Generated by Django 5.2.11 on 2026-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_vacancy_max_hires'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='verification_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='verification_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('suspicious', 'Suspicious'), ('mismatch', 'Mismatch')], max_length=20, null=True),
        ),
    ]
