# Generated by Django 5.2.11 on 2026-03-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_candidate_github_url_candidate_verification_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fairness_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='negotiation_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary_suggestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
