# Generated by Django 5.2.11 on 2026-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_candidate_fairness_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_counter_offer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='negotiation_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offered_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('ai_rejected', 'AI Rejected'), ('hr_pending', 'HR Pending'), ('offered', 'Offer Received'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('fired', 'Fired')], default='applied', max_length=20),
        ),
    ]
